version: '3'
services:
    db:
        image: postgres:11.4-alpine
        environment:
            POSTGRES_PASSWORD: 1234
            POSTGRES_USER: espe
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        container_name: db
    web:
        build: .
        command: uvicorn main:app --host 0.0.0.0 --reload
        working_dir: /tmp/app
        volumes:
            - ./app:/tmp/app
        ports:
            - '8000:8000'
        container_name: web
